"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
console.log("=== 08 number ===");
let num1 = 123;
let num2 = 0.123;
let num3 = -123;
console.log("1) num1: ", num1, num2, num3);
console.log("2) Max_value: ", Number.MAX_VALUE);
console.log("3) Min_value: ", Number.MIN_VALUE);
console.log("4) NaN: ", Number.NaN);
console.log("5) Infinity: ", Number.POSITIVE_INFINITY);
console.log("6) -Infinity: ", Number.NEGATIVE_INFINITY);
let notANumber = Number("syxy");
console.log("7) notANumber: ", notANumber);
console.log("8) isNaN: ", isNaN(notANumber));
let n = 188.12366666;
console.log("9) toFixed: ", n.toFixed(3));
console.log("10) toExponential: ", n.toExponential(3));
console.log("11) toPrecision: ", n.toPrecision(6));
console.log("12) toString: ", n.toString());
console.log("13) toLocaleString: ", n.toLocaleString());
console.log("14) valueOf: ", n.valueOf());
